apiVersion: v1
kind: Service
metadata:
  labels:
    run: modeloclsdsa-service
  name: modeloclsdsa-service
spec:
  ports:
    - port: 8501
      targetPort: 8501
      name: restapi
    - port: 8500
      targetPort: 8500
      name: grpc
  selector:
    app: modeloclsdsa-deployment
  type: LoadBalancer